# Generated by Django 4.0.5 on 2023-05-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='payment',
            field=models.CharField(choices=[('C', 'CASH'), ('A', 'CREDIT CARD'), ('B', 'CHEQUE')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='service',
            field=models.CharField(choices=[('C', 'CONFERENCE HALL'), ('A', 'ACCOMMODATION'), ('E', 'EVENT HALL')], default='A', max_length=1),
        ),
    ]
